<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Rimatv.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\iptv.Domain\iptv.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="_Common\Contracts\" />
    <Folder Include="_Common\DTOs\Updates\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="_ChannelRegistry\Seed\channel_registry.seed.json" />
  </ItemGroup>

</Project>
