//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M1Mentor.Utilities.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("M1Mentor.Utilities.Exceptions.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط اکانت کاربران فعال قابل ویرایش .
        /// </summary>
        public static string ActiveAccountCanBeEdited {
            get {
                return ResourceManager.GetString("ActiveAccountCanBeEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط جشنواره فعال را میتوان اپدیت کرد .
        /// </summary>
        public static string ActiveFestivalCanBeUpdated {
            get {
                return ResourceManager.GetString("ActiveFestivalCanBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این کاربر سفارش فعال وجود دارد..
        /// </summary>
        public static string ActiveOrderExistsForUser {
            get {
                return ResourceManager.GetString("ActiveOrderExistsForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط اکانت کاربران فعال قابل مسدود شدن میباشد .
        /// </summary>
        public static string ActiveUserCanBeBanned {
            get {
                return ResourceManager.GetString("ActiveUserCanBeBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط گذرواژه اکانت کاربران فعال را میتوان تغییر داد .
        /// </summary>
        public static string ActiveUserPasswordCanBeChanged {
            get {
                return ResourceManager.GetString("ActiveUserPasswordCanBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نظر قبلا پاسخ داده شده است .
        /// </summary>
        public static string AdviceAlreadyAnswerd {
            get {
                return ResourceManager.GetString("AdviceAlreadyAnswerd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست مشاوره یافت نشد.
        /// </summary>
        public static string AdviceNotFound {
            get {
                return ResourceManager.GetString("AdviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل یک جلسه باید وارد شود.
        /// </summary>
        public static string AtLeastOneSessionRequired {
            get {
                return ResourceManager.GetString("AtLeastOneSessionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات بدن یافت نشد .
        /// </summary>
        public static string BodyDetailNotFound {
            get {
                return ResourceManager.GetString("BodyDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ایجاد این برنامه وجود ندارد.
        /// </summary>
        public static string CannotCreatePlan {
            get {
                return ResourceManager.GetString("CannotCreatePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر فعال را نمی توان پاک کرد .
        /// </summary>
        public static string CannotDeleteActiveUser {
            get {
                return ResourceManager.GetString("CannotDeleteActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش قبلاً پرداخت شده و قابل حذف نیست..
        /// </summary>
        public static string CannotDeletePaidOrder {
            get {
                return ResourceManager.GetString("CannotDeletePaidOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این اطلاعات برنامه ای ثبت شده است.
        /// </summary>
        public static string CannotDeleteUsedBodyDetail {
            get {
                return ResourceManager.GetString("CannotDeleteUsedBodyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حرکتی که در برنامه ای استفاده شاده باشد .
        /// </summary>
        public static string CannotDeleteUsedMovement {
            get {
                return ResourceManager.GetString("CannotDeleteUsedMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حرکت نمی تواند وارث خود باشد .
        /// </summary>
        public static string CategoryCantBeItsOwnParent {
            get {
                return ResourceManager.GetString("CategoryCantBeItsOwnParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید منقضی شده است .
        /// </summary>
        public static string CodeExpired {
            get {
                return ResourceManager.GetString("CodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید اشتباه میباشد .
        /// </summary>
        public static string CodeIsWrong {
            get {
                return ResourceManager.GetString("CodeIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه غذایی در حال حاضر وجود دارد .
        /// </summary>
        public static string DietPlanAlreadyExsist {
            get {
                return ResourceManager.GetString("DietPlanAlreadyExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه غذایی یافت نشد .
        /// </summary>
        public static string DietPlanNotFound {
            get {
                return ResourceManager.GetString("DietPlanNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این برنامه غذایی در یک برنامه ثبت شده است .
        /// </summary>
        public static string DIetPlanUsedInPlan {
            get {
                return ResourceManager.GetString("DIetPlanUsedInPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف نمیتواند کمتر از 0 درصد باشد .
        /// </summary>
        public static string DiscountCannotBeLessThan {
            get {
                return ResourceManager.GetString("DiscountCannotBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف نمیتواند بیشتر از 100 درصد باشد .
        /// </summary>
        public static string DiscountCannotBeMoreThan {
            get {
                return ResourceManager.GetString("DiscountCannotBeMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در دسته بندی مورد نظر حرکتی با چنین مشخصات ثبت شده است.
        /// </summary>
        public static string DuplicateMovementInDestenationParrent {
            get {
                return ResourceManager.GetString("DuplicateMovementInDestenationParrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با این شماره همراه قبلا ثبت نام کرده است .
        /// </summary>
        public static string DuplicateRegister {
            get {
                return ResourceManager.GetString("DuplicateRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فستیوال یافت نشد .
        /// </summary>
        public static string FestivalNotFound {
            get {
                return ResourceManager.GetString("FestivalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب جلسات نادرست است. شماره جلسه مورد انتظار: {0}، اما شماره وارد شده: {1}.
        /// </summary>
        public static string InvalidSessionSequence {
            get {
                return ResourceManager.GetString("InvalidSessionSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حرکت با چنین مشخصات وجود دارد .
        /// </summary>
        public static string MovementAlredyExsists {
            get {
                return ResourceManager.GetString("MovementAlredyExsists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این دسته بندی قبلا ثبت شده است .
        /// </summary>
        public static string MovementCategoryAlreadyEsist {
            get {
                return ResourceManager.GetString("MovementCategoryAlreadyEsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی یافت نشد.
        /// </summary>
        public static string MovementCategoryNotFound {
            get {
                return ResourceManager.GetString("MovementCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حرکت یافت نشد .
        /// </summary>
        public static string MovementNotFound {
            get {
                return ResourceManager.GetString("MovementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تکرار برای همه ست ها وارد نشده .
        /// </summary>
        public static string NotAllrepetitionsEntered {
            get {
                return ResourceManager.GetString("NotAllrepetitionsEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه قدیمی اشتباه است .
        /// </summary>
        public static string OldPasswordIsWrong {
            get {
                return ResourceManager.GetString("OldPasswordIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنها یک جشنواره فعال میتوان داشت .
        /// </summary>
        public static string OnlyOneActiveFestivalCanExsist {
            get {
                return ResourceManager.GetString("OnlyOneActiveFestivalCanExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش قبلاً پرداخت شده و قابل ویرایش نیست..
        /// </summary>
        public static string OrderAlreadyPaid {
            get {
                return ResourceManager.GetString("OrderAlreadyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این سفارش، برنامه‌ای ثبت نشده است.
        /// </summary>
        public static string OrderDoesNotHavePlan {
            get {
                return ResourceManager.GetString("OrderDoesNotHavePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش شما منقضی شده است.
        /// </summary>
        public static string OrderExpired {
            get {
                return ResourceManager.GetString("OrderExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت پرداخت برای این سفارش وجود ندارد..
        /// </summary>
        public static string OrderInvalidStateForPayment {
            get {
                return ResourceManager.GetString("OrderInvalidStateForPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش یافت نشد.
        /// </summary>
        public static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از تمام خدمات پلن خود استفاده کرده‌اید.
        /// </summary>
        public static string OrderUsed {
            get {
                return ResourceManager.GetString("OrderUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی که ریشه یک دسته بندی دیگر باشد را نمی توان حذف کرد .
        /// </summary>
        public static string ParentCategoryCanntBeDeleted {
            get {
                return ResourceManager.GetString("ParentCategoryCanntBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی والد یافت نشده .
        /// </summary>
        public static string ParentMovementCategoryNotFound {
            get {
                return ResourceManager.GetString("ParentMovementCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه یکبار مصرف هر 5 دقیقه یکبار میتوان ارسال شود .
        /// </summary>
        public static string PaswordSend {
            get {
                return ResourceManager.GetString("PaswordSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً ابتدا سفارش خود را پرداخت کنید.
        /// </summary>
        public static string PayOrder {
            get {
                return ResourceManager.GetString("PayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واریزی در حال انتظار یافت نشد..
        /// </summary>
        public static string PendingDepositNotFound {
            get {
                return ResourceManager.GetString("PendingDepositNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه قبلا تایید شده است .
        /// </summary>
        public static string PhoneNumberIsActive {
            get {
                return ResourceManager.GetString("PhoneNumberIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کاربر تایید نشده است .
        /// </summary>
        public static string PhoneNumberNotActive {
            get {
                return ResourceManager.GetString("PhoneNumberNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه‌ای با این شناسه یافت نشد.
        /// </summary>
        public static string PlanNotFound {
            get {
                return ResourceManager.GetString("PlanNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارشی با این مرجع پرداخت و وضعیت معتبر یافت نشد.
        /// </summary>
        public static string RelatedOrderNotFound {
            get {
                return ResourceManager.GetString("RelatedOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تکرار نمی تواند کمتر از 0 باشد .
        /// </summary>
        public static string RepetitionsCannotBe {
            get {
                return ResourceManager.GetString("RepetitionsCannotBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش یافت نشد .
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جلسه مورد نظر یافت نشد.
        /// </summary>
        public static string SessionNotFound {
            get {
                return ResourceManager.GetString("SessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد ست نمی تواند بیشتر از 60 یا کمتر از 0 باشد .
        /// </summary>
        public static string SetsCannotBe {
            get {
                return ResourceManager.GetString("SetsCannotBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اس ام اس هر 2 دقیقه یک بار میتواند ارسال شود .
        /// </summary>
        public static string SMSTime {
            get {
                return ResourceManager.GetString("SMSTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعضی از حرکات در دسترس نمی باشند.
        /// </summary>
        public static string SomeMovementsNotFound {
            get {
                return ResourceManager.GetString("SomeMovementsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این حرکت، سوپرست مشخص نشده است.
        /// </summary>
        public static string SupersetNotSet {
            get {
                return ResourceManager.GetString("SupersetNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این تعریف قبلا ثبت شده است .
        /// </summary>
        public static string TariffAlreadyExsist {
            get {
                return ResourceManager.GetString("TariffAlreadyExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت تعرفه مشخص نشده .
        /// </summary>
        public static string TariffDurationNotSet {
            get {
                return ResourceManager.GetString("TariffDurationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این تعریف در سفارشی استفاده شده است .
        /// </summary>
        public static string TariffIsUsedInOrder {
            get {
                return ResourceManager.GetString("TariffIsUsedInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعرفه یافت نشد .
        /// </summary>
        public static string TariffNotFound {
            get {
                return ResourceManager.GetString("TariffNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این دسته بندی در یکی از حرکت ها استفاده شده است .
        /// </summary>
        public static string ThisCategoryIsUsedInMovement {
            get {
                return ResourceManager.GetString("ThisCategoryIsUsedInMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر اجازه دسترسی به این سفارش را ندارد..
        /// </summary>
        public static string UserCannotAccessOrder {
            get {
                return ResourceManager.GetString("UserCannotAccessOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان دسترسی برای کاربر ممکن نسیت.
        /// </summary>
        public static string UserCannotAccessThis {
            get {
                return ResourceManager.GetString("UserCannotAccessThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر درحال حاضر سفارش فعالی ندارد.
        /// </summary>
        public static string UserDontHaveActiveOrdrer {
            get {
                return ResourceManager.GetString("UserDontHaveActiveOrdrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکانت کاربر مسدود میباشد .
        /// </summary>
        public static string UserIsBan {
            get {
                return ResourceManager.GetString("UserIsBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر یافت نشد .
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا از لینک معتبر استفاده کنید.
        /// </summary>
        public static string UseValidLink {
            get {
                return ResourceManager.GetString("UseValidLink", resourceCulture);
            }
        }
    }
}
